#!/bin/bash
#####################################################################################################
# SCRIPT : To be used to ecrypt password used in property file for check_hadoop utility
# USAGE  : passwd_util
# DATED  : 25 June, 2016
# VERSION: 1.0
#####################################################################################################

stty_orig=`stty -g`
stty -echo
read -p "- Please provide password to encrypt: " user_password
stty $stty_orig

echo ""
echo "- Your encrypted password is:"
echo ${user_password} | openssl enc -aes-256-cbc -a -salt -pass pass:Sankar
